### ISSUE TITLE
unexpected token const 

### ISSUE THREAD

**Issue by eaxxoi** [Arze1/CSGO-Overpay-Bot#35]
C:\Users\Liam>node C:\Users\Liam\Desktop\andagain\bot.js
C:\Users\Liam\Desktop\andagain\bot.js:31
*/ const url = require 'https://api.steamapi.io/market/prices/'+config.options.appid+'?
  ^^^^^key='+config.options.apikey;

SyntaxError: Unexpected token const

**Comment by FreddyFish** [comment]
Do you have the newest bot.js?

**Comment by eaxxoi** [comment]
i just got it now but it still doesnt work
same error

**Comment by eaxxoi** [comment]
C:\Users\Liam\Desktop\abc\bot.js:33
const priceUrl = 'https://api.steamapi.io/market/prices/'+config.options.appid+'?
^^^^^key='+config.options.apikey;
SyntaxError: Unexpected token const

**Comment by FreddyFish** [comment]
How do you run the script? We need some more information.
Also please tell me what node version you are using (node -v)

**Comment by eaxxoi** [comment]
7.7.4

**Comment by eaxxoi** [comment]
i run it like: node c:user\desktop\bot\bot.js

**Comment by w3bb0** [comment]
Try cd to the folder then do bot.js and send us Ur config nothing in it off
so we can look at the syntax

**Comment by eaxxoi** [comment]
how do i do it ?

**Comment by w3bb0** [comment]
Just copy and paste it and for the folders go like

Cd desktop
Cd folder name

On 27 Mar 2017 08:10, "eaxxoi" <notifications@github.com> wrote:

how do i do it ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Arze1/CSGO-Overpay-Bot/issues/35#issuecomment-289371457>,
or mute the thread

**Comment by eaxxoi** [comment]
in the command prompt

**Comment by w3bb0** [comment]
So
Cd desktop
Cd bot
Node bot.js

**Comment by eaxxoi** [comment]
in the command prompt?

**Comment by w3bb0** [comment]
Yes so cd to folder then
Npm install
Node bot.js

On 27 Mar 2017 08:20, "eaxxoi" <notifications@github.com> wrote:

in the command prompt?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Arze1/CSGO-Overpay-Bot/issues/35#issuecomment-289373299>,
or mute the thread

**Comment by eaxxoi** [comment]
npm intall ? what am i supose to install ? sorry i am new to coding

**Comment by eaxxoi** [comment]
ill try it when i get home thank you

**Comment by w3bb0** [comment]
No problem next time read the read me first

**Comment by ezraripps** [comment]
You install the dependencys that interact with steam

**Comment by ezraripps** [comment]
Issue has been solved, he wasn't using node
